---
- name: Generate and Apply SD-WAN configuration to SRX
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf"
    credentials:
      host: "{{ inventory_hostname }}"
      username: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      timeout: 150
  
  vars_prompt:
    - name: USERNAME
      prompt: SRX Username
      private: no

    - name: PASSWORD
      prompt: Password
      private: yes

  tasks:
    - name: confirm or create config directory 
      file:
        path: "{{ tmp_dir }}"
        state: directory
    - name: include vars from <hostname>.yml
      include_vars:
        file: "{{vars_filepath}}"
        name: "{{vars_filename}}"
      register: value


    - name: Display Vars
      debug: var=value

    - name: save device information using template
      template:
        src: "{{ template }}"
        dest: "{{ conf_file }}"

    #- name: display 
    #  debug: 
    #    var: vars
    
    - name: Merge configuration data from a file and commit
      juniper_junos_config:
        provider: "{{ credentials }}"
        savedir: "{{ playbook_dir }}"
        load: "override"
        format: "text"
        src: "{{ conf_file }}"
        comment: "Configuring SD-WAN with Ansible Playbooks"
         
      register: response

    - name: Print the response
      debug: 
        var: response

    - name: Configure LTE profile ID 
      juniper_junos_command:
        provider: "{{ credentials }}"
        commands: "request modem wireless create-profile profile-id 10 access-point-name {{ apn_name }} cl-{{ mpim_slot }}/0/0 slot {{ mpim_slot }}"
      register: profileval

    - name: Print profileval
      debug:
        var: profileval
